### PR TITLE
added support for GET, LIST, and DELETE Sights and for sharing Sights

### PR DESCRIPTION
**Pull request by daveskull81**
I followed the conventions in the SDK as it is built for requests against sheets and reports. As there aren't any specific tests to run I tested each request manually and got expected results from each. 
I only added support specifically to GET a sight by id, List All Sights, and to DELETE sight.
I manually tested each of sharing end points and they worked as expected for sights.

### CODE REVIEW

**Comment by activescott** [comment]
@daveskull81 IMHO I'd love to see some tests for this however primitive. See the tests in `smartsheet-javascript-sdk/test/utils.js` for some of examples of how to do this with mocks. If you want a hand putting this together - I'm more than happy to help- lets just setup time to sync and I'll sit down and help out for an hour or so.

**Comment by stmcallister** [comment]
Looks great, @daveskull81 ! Thanks for doing that. Could you also add entries to the [ExampleUsage.md](https://github.com/smartsheet-platform/smartsheet-javascript-sdk/blob/master/ExampleUsage.md)? Thanks!

**Comment by activescott** [comment]
@daveskull81 Something like this...
[sights.js.txt](https://github.com/smartsheet-platform/smartsheet-javascript-sdk/files/886678/sights.js.txt)

**Comment by daveskull81** [comment]
I have updated the tests for the sdk to include the new sights requests I implemented. Testing is done to ensure methods are present and give the expected response. I placed these tests in the client.js file to continue the conventions of the sdk and display test results in the same format as the other existing tests.
In the Example.md file I added request examples in a similar method.

**Comment by activescott** [comment]
@daveskull81 Love the tests. Nice work!

**Pull request merged**
